server:
  port: 9095
logging:
  config: classpath:logback.xml
  level:
    org.springframework.cloud.gateway: debug
    com.xiaomi.gateway: info
#---------------单纯的配置yaml格式的路由-------------------
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: middle-community-rest-userinfo-get
#          #          uri: http://localhost:8080 # 当访问spring-cloud-gateway uri + predicates中的路径时会转发到这个uri + predicates中的路径
#          uri: http://staging-middle-community.inf.miui.srv
#          predicates:
#            - Method=GET  #老恶心了，这里所有的key=value中间不能有空格，否则报错
#            - Path=/userinfo,/userinfo/search,/userinfo/batch
#        - id: middle-community-rest-userinfo-post
#          uri: http://staging-middle-community.inf.miui.srv
#          predicates:
#            - Method=POST
#            - Path=/userinfo
#----------------使用nacos discovery 将producer服务和gateway都注册到nacos---------------------------
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848    # nacos服务器的地址
        namespace: 4b9f96c5-ff53-44ba-9151-8bbf45150060
        cluster-name: newstaging
    gateway:
      routes:
        - id: nacos-route #这条predications的id
          uri: lb://middle-community-rest # lb表示负载均衡 middle-community-rest表示producer在nacos注册的服务id
          predicates:
            - Path=/**
management:
  endpoints:
    web:
      exposure:
        include: "*"